name: Manual Formula Update

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'KPF version to update to'
        required: true
        type: string

jobs:
  manual-update:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install homebrew-pypi-poet
        run: |
          python -m pip install --upgrade pip
          pip install homebrew-pypi-poet

      - name: Generate formula
        run: |
          VERSION="${{ github.event.inputs.version }}"
          
          # Get package info from PyPI
          python3 << 'PYTHON_EOF'
          import json
          import requests
          
          version = "${{ github.event.inputs.version }}"
          response = requests.get(f'https://pypi.org/pypi/kpf/{version}/json')
          data = response.json()
          
          # Find source distribution
          for url_info in data['urls']:
              if url_info['packagetype'] == 'sdist':
                  url = url_info["url"]
                  sha256 = url_info["digests"]["sha256"]
                  break
          
          # Create the formula
          formula_content = f'''class Kpf < Formula
            include Language::Python::Virtualenv

            desc "A terminal utility to run kubectl port-forward and automatically restart it when endpoint changes are detected"
            homepage "https://github.com/jessegoodier/kpf"
            url "{url}"
            sha256 "{sha256}"
            license "MIT"

            depends_on "python@3.12"

            def install
              virtualenv_create(libexec, "python3.12")
              
              # Install kpf and its dependencies directly from PyPI using wheels
              # This bypasses all the build system compatibility issues
              system libexec/"bin/python", "-m", "pip", "install", "kpf=={version}"
              
              # Create binary symlink
              bin.install_symlink libexec/"bin/kpf"
            end

            test do
              # Test that the kpf command exists and shows help
              assert_match "A better Kubectl Port-Forward", shell_output("#{bin}/kpf --help")
              
              # Test version output
              version_output = shell_output("#{bin}/kpf --version")
              assert_match "kpf #{version}", version_output
            end
          end'''
          
          # Write the formula
          with open('Formula/kpf.rb', 'w') as f:
              f.write(formula_content)
          
          print("Generated formula:")
          print(formula_content)
          PYTHON_EOF

      - name: Show final formula
        run: |
          echo "Final formula content:"
          cat Formula/kpf.rb

      - name: Test formula syntax
        run: |
          # Basic syntax check
          ruby -c Formula/kpf.rb

      - name: Commit and push
        run: |
          VERSION="${{ github.event.inputs.version }}"
          
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          git add Formula/kpf.rb
          git commit -m "Manually update kpf to version $VERSION

          🔧 Manual update via GitHub Actions workflow
          
          Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          
          git push